name: hpt_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - filelock=3.20.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h5py=3.15.1
  - hdf5=1.14.6
  - icu=75.1
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libaec=1.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openssl=3.6.0
  - pandas=2.3.3
  - pip=25.3
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - sympy=1.14.0
  - tk=8.6.13
  - torchaudio=2.2.2
  - torchtriton=2.2.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - audioread==3.1.0
      - azure-common==1.1.28
      - azure-core==1.36.0
      - azure-storage-blob==12.27.1
      - babel==2.17.0
      - backports-zstd==1.0.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - bokeh==3.8.1
      - boto3==1.40.73
      - botocore==1.40.73
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2026.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.11
      - importlib-resources==6.5.2
      - intervaltree==3.2.1
      - invoke==2.2.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - isodate==0.7.2
      - isoduration==20.11.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.45.1
      - madmom==0.16.1
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mido==1.3.3
      - mir-eval==0.8.2
      - mirdata==1.0.0
      - mistune==3.1.4
      - msgpack==1.1.2
      - narwhals==2.14.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nnaudio==0.3.4
      - note-seq==0.0.5
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numba==0.62.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - paramiko==4.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - pretty-midi==0.2.11
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyfluidsynth==1.3.4
      - pygments==2.19.2
      - pynacl==1.6.1
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - s3transfer==0.14.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.44.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.3.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-inspection==0.4.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.23.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - wrapt==2.0.1
      - xyzservices==2025.11.0
